version: '3.4'
services:
  weaviate:
    image: docker.io/semitechnologies/weaviate:1.24.14
    restart: on-failure:0
    ports:
      - "8080:8080"
      - "50051:50051"
    volumes:
      - /var/weaviate:/var/lib/weaviate

    environment:
      LOG_LEVEL: "debug"
      QUERY_DEFAULTS_LIMIT: 20
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      DEFAULT_VECTORIZER_MODULE: multi2vec-clip
      CLIP_INFERENCE_API: "http://multi2vec-clip:8080"
      ENABLE_MODULES: "multi2vec-clip, backup-filesystem"
      BACKUP_FILESYSTEM_PATH: "/var/lib/weaviate/backups"


  multi2vec-clip:
    image: docker.io/semitechnologies/multi2vec-clip:xlm-roberta-base-ViT-B-32-laion5b_s13b_b90k-1.2.0
